name: "Conventional PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate Pull Request Title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # fix:   bug fix on prod code
          # feat:  new feature on prod code
          # test:  only modify test or test utils
          # doc:   only modify docs/comments
          # chore: anything else
          types: |
            fix
            feat
            test
            doc
            chore
